### ISSUE TITLE
Error:(30, 13) Failed to resolve: com.github.8tory:json2notification:-SNAPSHOT

### ISSUE THREAD

**Issue by gustavomc** [8tory/AndroidNotificationJson#2]
Error:(30, 13) Failed to resolve: com.github.8tory:json2notification:-SNAPSHOT
Show in File
Show in Project Structure dialog

**Comment by yongjhih** [comment]
Thanks for your report, we're looking. You can use jcenter instead of jitpack.

``` gradle
repositories {
    jcenter()
}

dependencies {
    compile 'com.infstory:json2notification:1.0.0'
}
```

**Comment by gustavomc** [comment]
ok thanks it worked
