### ISSUE TITLE
is there any way to set vibration?

### ISSUE THREAD

**Issue by gustavomc** [8tory/AndroidNotificationJson#4]
i want to control vibration

**Comment by gustavomc** [comment]
hi, thanks for your help, i only have 2 questions

1.- how can i open my app main activity calling it from the json
2.- how can i set vibration from the json

**Comment by yongjhih** [comment]
1. See also: https://github.com/8tory/json2notification/blob/master/json2notification-app/src/main/java/json2notification/app/MainActivity.java
2. Add the following line: `"vibrate": [1000, 1000, 1000, 1000, 1000]`, see also: https://github.com/8tory/json2notification/blob/master/json2notification-app/src/main/assets/wiki.json
