### ISSUE TITLE
UIL doesn't support scheme(protocol) by default

### ISSUE THREAD

**Issue by gustavomc** [8tory/AndroidNotificationJson#5]
why im getting this?
 E/ImageLoader﹕ UIL doesn't support scheme(protocol) by default [R.mipmap.ic_notification]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))
 java.lang.UnsupportedOperationException: UIL doesn't support scheme(protocol) by default [R.mipmap.ic_notification]. You should implement this support yourself (BaseImageDownloader.getStreamFromOtherSource(...))

**Comment by yongjhih** [comment]
Move mipmap/ic_notification to drawable/. We used image loader that's not support mipmap right now.
